package org.xmlet.htmlflow.datastar.expressions

/**
 * Represents a [DataStarExpression] that is generated by an operation provided by the DSL,
 * rather than by a Datastar action, such as the infix JavaScript operator helpers.
 */
class DataStarExpressionOp internal constructor(
    expression: String,
) : DataStarExpression(expression)
