package org.xmlet.htmlflow.datastar.expressions

/**
 * Represents a [DataStarExpression] that is generated by an operation provided by the DSL,
 *  that are not actions, such as the infix functions.
 *
 * @property expression The raw String representation of the expression to be evaluated
 *  and processed by the DataStar framework.
 */
class DataStarExpressionOp internal constructor(
    val expression: String,
) : DataStarExpression(expression)
