package org.xmlet.htmlflow.datastar.expressions

/**
 * Represents a [DataStarExpression] that is generated by an operation provided by the DSL,
 * rather than by a Datastar action, such as the infix JavaScript operator helpers.
 *
 * @property expression The expression syntax to be evaluated and processed by the Datastar framework.
 * @property precedence JavaScript precedence for this operation, used to parenthesize composed operands.
 */
class DataStarExpressionOp internal constructor(
    val expression: String,
    override val precedence: Int = ExpressionPrecedence.PRIMARY,
) : DataStarExpression(expression)
