package pt.isel.views.htmlflow

import htmlflow.doc
import htmlflow.html
import jakarta.ws.rs.Path
import org.xmlet.htmlapifaster.EnumTypeInputType
import org.xmlet.htmlapifaster.EnumTypeScriptType
import org.xmlet.htmlapifaster.body
import org.xmlet.htmlapifaster.div
import org.xmlet.htmlapifaster.head
import org.xmlet.htmlapifaster.input
import org.xmlet.htmlapifaster.label
import org.xmlet.htmlapifaster.p
import org.xmlet.htmlapifaster.script
import org.xmlet.htmlapifaster.table
import org.xmlet.htmlapifaster.tbody
import org.xmlet.htmlapifaster.td
import org.xmlet.htmlapifaster.tr
import pt.isel.datastar.events.Blur
import pt.isel.datastar.events.Focus
import pt.isel.datastar.expressions.not
import pt.isel.datastar.extensions.dataAttr
import pt.isel.datastar.extensions.dataBind
import pt.isel.datastar.extensions.dataInit
import pt.isel.datastar.extensions.dataOn
import pt.isel.datastar.extensions.dataSignal

val hfDBmon =
    StringBuilder()
        .apply {
            doc {
                html {
                    head {
                        script {
                            attrType(EnumTypeScriptType.MODULE)
                            attrSrc("https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-RC.5/bundles/datastar.js")
                        }
                    }
                    body {
                        div {
                            attrId("demo")
                            dataInit { +get(::updates) }
                            val editing =
                                dataSignal("editing", false) {
                                    modifiers { ifMissing() }
                                }
                            p {
                                text("Average render time for entire page: { renderTime }")
                            }
                            div {
                                addAttr("role", "group")
                                label {
                                    text("Mutation Rate %")
                                    input {
                                        attrType(EnumTypeInputType.NUMBER)
                                        attrMin("0")
                                        attrMax("100")
                                        attrValue("20")
                                        dataOn(Focus) {
                                            +(editing setValue true)
                                        }
                                        dataOn(Blur) {
                                            +put(::inputs)
                                            +(editing setValue false)
                                        }
                                        val mutationRate = dataBind("mutation-rate")
                                        dataAttr("data-bind:${mutationRate.name}") { +editing }
                                        val mutRate = dataBind("_mutation-rate")
                                        dataAttr("data-bind:${mutRate.name}") { +!editing }
                                    }
                                }
                                label {
                                    text("FPS")
                                    input {
                                        attrType(EnumTypeInputType.NUMBER)
                                        attrMin("1")
                                        attrMax("144")
                                        attrValue("60")
                                        dataOn(Focus) {
                                            +(editing setValue true)
                                        }
                                        dataOn(Blur) {
                                            +put(::inputs)
                                            +(editing setValue false)
                                        }
                                        val framesPerSecond = dataBind("fps")
                                        dataAttr("data-bind:${framesPerSecond.name}") { +editing }
                                        val fps = dataBind("_fps")
                                        dataAttr("data-bind:${fps.name}") { +!editing }
                                    }
                                }
                            }
                            table {
                                attrStyle("table-layout: fixed; width: 100%; word-break: break-all")
                                tbody {
                                    comment("Dynamic rows generated by server")
                                    tr {
                                        td { text("cluster1") }
                                        td {
                                            attrStyle("background-color: var(--_active-color)")
                                            attrClass("success")
                                            text("8")
                                        }
                                        td {
                                            addAttr("aria-description", "SELECT blah from something")
                                            text("12ms")
                                        }
                                        comment("More query cells...")
                                    }
                                    comment("More database rows...")
                                }
                            }
                        }
                    }
                }
            }
        }.toString()

@Path("/dbmon/updates")
private fun updates() {}

@Path("/dbmon/inputs")
private fun inputs() {}
